Sprint 26 odim 3328
amar-shalgar/ODIM pull request #3
Opened 2020-09-08 08:20 UTC by amar-shalgar

Implemented create volume and updated unit tests 

Below is the unit test report for svc-api and svc-systems
/ODIM/svc-systems$ go test ./... -race
?       github.com/ODIM-Project/ODIM/svc-systems        [no test files]
ok      github.com/ODIM-Project/ODIM/svc-systems/chassis        1.315s
ok      github.com/ODIM-Project/ODIM/svc-systems/rpc    2.106s
ok      github.com/ODIM-Project/ODIM/svc-systems/scommon        121.685s
?       github.com/ODIM-Project/ODIM/svc-systems/sconstant      [no test files]
ok      github.com/ODIM-Project/ODIM/svc-systems/smodel 1.596s
?       github.com/ODIM-Project/ODIM/svc-systems/sresponse      [no test files]
ok      github.com/ODIM-Project/ODIM/svc-systems/systems        1.812s

ODIM/svc-systems$ go test ./... -count=1
?       github.com/ODIM-Project/ODIM/svc-systems        [no test files]
ok      github.com/ODIM-Project/ODIM/svc-systems/chassis        0.481s
ok      github.com/ODIM-Project/ODIM/svc-systems/rpc    0.857s
ok      github.com/ODIM-Project/ODIM/svc-systems/scommon        60.997s
?       github.com/ODIM-Project/ODIM/svc-systems/sconstant      [no test files]
ok      github.com/ODIM-Project/ODIM/svc-systems/smodel 0.926s
?       github.com/ODIM-Project/ODIM/svc-systems/sresponse      [no test files]
ok      github.com/ODIM-Project/ODIM/svc-systems/systems        0.473s

/ODIM/svc-api$ go test ./... -race
?       github.com/ODIM-Project/ODIM/svc-api    [no test files]
ok      github.com/ODIM-Project/ODIM/svc-api/handle     1.467s
?       github.com/ODIM-Project/ODIM/svc-api/messages   [no test files]
?       github.com/ODIM-Project/ODIM/svc-api/middleware [no test files]
?       github.com/ODIM-Project/ODIM/svc-api/models     [no test files]
?       github.com/ODIM-Project/ODIM/svc-api/response   [no test files]
?       github.com/ODIM-Project/ODIM/svc-api/router     [no test files]
?       github.com/ODIM-Project/ODIM/svc-api/rpc        [no test files]
/ODIM/svc-api$ go test ./... -count=1
?       github.com/ODIM-Project/ODIM/svc-api    [no test files]
ok      github.com/ODIM-Project/ODIM/svc-api/handle     0.091s
?       github.com/ODIM-Project/ODIM/svc-api/messages   [no test files]
?       github.com/ODIM-Project/ODIM/svc-api/middleware [no test files]
?       github.com/ODIM-Project/ODIM/svc-api/models     [no test files]
?       github.com/ODIM-Project/ODIM/svc-api/response   [no test files]
?       github.com/ODIM-Project/ODIM/svc-api/router     [no test files]
?       github.com/ODIM-Project/ODIM/svc-api/rpc        [no test files]

2020-09-08 08:35 UTC, hemantha-beecherla approved these changes
LGTM

2020-09-08 08:53 UTC, a-ajith approved these changes

2020-09-08 09:01 UTC, jeevan-kamkar requested changes
Please address the changes

2020-09-08 09:01 UTC, jeevan-kamkar commented on svc-api/handle/systems_test.go
> +			StatusCode:    400,
instead of using statuscode directly use http package

2020-09-08 09:31 UTC, amar-shalgar commented on svc-api/handle/systems_test.go
> +			StatusCode:    400,
Addressed the comments

2020-09-08 09:51 UTC, jeevan-kamkar approved these changes
LGTM

2020-09-08 13:57 UTC, irappa-pattar approved these changes

2020-09-09 08:05 UTC, shivacharanms approved these changes

2020-09-09 08:13 UTC, merged