Added routes for NetworkDeviceFunctions and NetworkPorts
amar-shalgar/ODIM pull request #9
Opened 2020-11-18 12:42 UTC by amar-shalgar

This PR is part of #239

2020-11-18 12:45 UTC, a-ajith requested changes

2020-11-18 12:45 UTC, a-ajith commented on svc-api/router/router.go
> +    chassis.Get("/{id}/NetworkAdapters/{rid}/NetworkPorts", cha.GetChassisResource)
please apply go tools

2020-11-18 12:56 UTC, amar-shalgar commented on svc-api/router/router.go
> +    chassis.Get("/{id}/NetworkAdapters/{rid}/NetworkPorts", cha.GetChassisResource)
Addressed review comments

2020-11-18 12:57 UTC, a-ajith approved these changes

2020-11-19 03:23 UTC, jeevan-kamkar approved these changes
IMHO the same routes need to be added to GRF plugin please update the same

2020-11-19 04:43 UTC, irappa-pattar approved these changes

2020-11-19 04:51 UTC, bharath-b-hpe approved these changes
Please run go tools.

2020-11-19 08:11 UTC, Bharath-KKB approved these changes

2020-11-19 08:11 UTC, merged